### ISSUE TITLE
Chrome Uncaught TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by adamtheapiguy** [TarekRaafat/autoComplete.js#423]
### Discussed in https://github.com/TarekRaafat/autoComplete.js/discussions/422

<div type='discussions-op-text'>

<sup>Originally posted by **adamtheapiguy** January 23, 2024</sup>
Hey guys,

I get the below error in chrome sometime when I click on an item in the drop-down list of autoComplete , any ideas?

<img width="1520" alt="Screenshot 2024-01-23 at 5 33 21 am" src="https://github.com/TarekRaafat/autoComplete.js/assets/11493202/bebb4e51-d6bd-4161-a6d4-8f161bbb6e6a">

Error Text:
========
autoComplete.js:333 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at feedback (autoComplete.js:333:28)
    at select (autoComplete.js:413:5)
    at click (autoComplete.js:422:7)
    at HTMLUListElement.click$1 (autoComplete.js:508:11)</div>

**Comment by TarekRaafat** [comment]
Hello @adamtheapiguy,

Apologies for my very delayed reply.

I have already responded to this in the Discussion #422. The error traces back to a lifecycle issue where the internal state is not populated at the time of selection.

This is now tracked in the roadmap:
- #455 (data source return validation)
- #482 (re-init teardown and select fix)

Feel free to vote on those issues if they matter to you.

Have a nice day, cheers! :)
