### ISSUE TITLE
rollup starting error

### ISSUE THREAD

**Issue by Tankerxyz** [TarekRaafat/autoComplete.js#6]
When I type `npm run dev` or `npm start` I have some rollup error.

```
> autocomplete.js@1.2.1 start /home/cubex/WebstormProjects/autoComplete.js
> rollup --watch "dev"

[!] TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Watcher.<anonymous> (/home/cubex/WebstormProjects/autoComplete.js/node_modules/rollup/bin/rollup:1783:42)
    at Watcher.emit (events.js:182:13)
    at Task.run (/home/cubex/WebstormProjects/autoComplete.js/node_modules/rollup/dist/rollup.js:26618:22)
    at /home/cubex/WebstormProjects/autoComplete.js/node_modules/rollup/dist/rollup.js:26531:70
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! autocomplete.js@1.2.1 start: `rollup --watch "dev"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the autocomplete.js@1.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cubex/.npm/_logs/2018-11-28T07_20_40_991Z-debug.log
```

**Comment by Tankerxyz** [comment]
I found that if downgrade node.js version from my 10.13 to 8.14, error is missing.
@TarekRaafat  Which version do you use?

**Comment by TarekRaafat** [comment]
I'm using node `v8.12.0`, most probably `npm start` is not working because it's set to `rollup --watch` and there are no configurations specified. In that case you have to change it to `rollup -c --watch` to read from the rollup config file which is basically same as `npm run dev`.

**Comment by Tankerxyz** [comment]
@TarekRaafat Yep, that's working for me, I will send pr.
